import subprocess
import validate
import matplotlib.pyplot as plt
import os
import json
import math
import sys
import pickle

def create_list_predicates(string):
	#print(string)
	p_list =[]
	tmp_str=""
	is_inside = False
	for c in string:
		#print(c) 
		#print(is_inside)
		#print(tmp_str)
		if c=="(":
			tmp_str+=c
			is_inside = True
		elif c==")":
			tmp_str+=c
			is_inside = False
		elif c == "," and not is_inside:
			#print("HERE")
			p_list.append(tmp_str)
			tmp_str=""
		else:
			tmp_str+=c

	if tmp_str!= "" and "!" not in tmp_str:
		p_list.append(tmp_str)


	return p_list

def process_equalities(path):
	f = open(path,"r")
	equalities = {}
	for line in f:
		print(line)
		slitted_line = line.split("=")
		arg1 =  slitted_line[0].strip()
		arg2 =  slitted_line[1].strip()
		equalities[arg1] = arg2
		equalities[arg2] = arg1
		

	f.close()
	return equalities

using_uniq_rules = False

print("Loading facts...\n")
facts =validate.process_literals("data/facts.txt")

print("Loading negatives...\n")
negatives = validate.process_literals("data/neg.txt")

print("Loading positives...\n")
positives = validate.process_literals("data/pos.txt")


print("Loading lifted random walks...\n")
lifted_rw = validate.process_lifted("data/lifted.tree")
#if not os.path.exists("data/lifted_uniq.tree"):
#	lifted_rw = validate.process_lifted("data/lifted.tree")
#	print("AS")
#else:
#	using_uniq_rules = True
#	print("IK")
#
#	
#	lifted_rw = validate.process_lifted("./data/lifted_uniq.tree")
#	print(len(lifted_rw))
	


equalities = process_equalities("data/equalities.txt")




#data consistence checker
num_lines = sum(1 for _ in open("data/facts.txt"))
is_facts_consistent = len(facts) == num_lines

num_lines = sum(1 for _ in open("data/neg.txt"))
is_negatives_consistent = len(negatives)==num_lines

num_lines = sum(1 for _ in open("data/pos.txt"))
is_positives_consistent = len(positives)==num_lines

num_lines = sum(1 for _ in open("data/lifted.tree"))
is_lifts_consistent = len(lifted_rw)==num_lines




#consistence with number of lines check
if not is_facts_consistent:
	raise Exception("Number of lines inconsistent with the number of facts")
if not is_negatives_consistent:
	raise Exception("Number of lines inconsistent with the number of negatives")
if not is_positives_consistent:
	raise Exception("Number of lines inconsistent with the number of positives")
if not is_lifts_consistent:
	raise Exception("Number of lines inconsistent with the number of lifts")



#take the name of the first positive predicate to take the target name
prediction_target = positives[0]["name"]

#Check existence of the file where the data generated by aleph would be
if not os.path.exists("Logs/LiftFINALLOG.txt"):
	raise Exception("Logs/LiftFINALLOG.txt missing")


log_file = "Logs/LiftFINALLOG.txt"
Log = open(log_file,"r")

####################################################
#
# READING ALEPH data
#
####################################################

log_file = "Logs/LiftFINALLOG.txt"
Log = open(log_file,"r")


#line counter debug effects
line =0

rule_list= []





#VARIABLES TO RESET
new_rule = {"head":"","tail":[],"positives":[],"negatives":[]}
tags_checker = {
	"consulting pos examples":False,
	"consulting neg examples":False,
	"hypothesis":False,
	"examples1":False,
	"examples2":False,	
}
hypothesis_reader =""
reading_hypothesis=False
reading_positives = False
reading_negatives = False
def checker_validate(checker):
	#print(checker)
	for key in checker.keys():
		if not checker[key]:
			raise Exception("[%s] tag not found on format file on line %d"%(key,line))

		


for l in Log:
	tmp = l.strip()
	line+=1
	#start to read a new rule
	
	#print("reading_positives: %d reading_negatives: %d reading_hypothesis: %d"%(reading_positives,reading_negatives,reading_hypothesis))
	
	if "A L E P H" in tmp:
		if new_rule["head"]!= "":
			checker_validate(tags_checker)

			rule_list.append(new_rule)
			#print(new_rule)
			


		#reset dictionaries
		new_rule = {"head":"","tail":[],"positives":[],"negatives":[]}
		tags_checker = {"consulting pos examples":False,"consulting neg examples":False,"hypothesis":False,"examples1":False,"examples2":False,	}
		reading_hypothesis=False
		reading_positives = False
		reading_negatives = False
		hypothesis_reader=""

	#Reat ALL TAGS
	elif len(tmp) > 0 and tmp[0] == "[":
		tmp = tmp.split("]")[0].replace("[","").strip()
		#print(tmp)

		if tmp == "hypothesis":
			tags_checker[tmp] =True
			reading_hypothesis= True

		elif tmp == "consulting pos examples":
			tags_checker[tmp] =True
		elif tmp == "consulting neg examples":
			tags_checker[tmp] =True

		elif tmp == "examples covered":
			reading_negatives=False
			
			if tags_checker["examples1"]:
				if tags_checker["examples2"]:
					Log.close()
					raise Exception("Unexpected tag found [%s]"%tmp)
				
				tags_checker["examples2"] = True
				
				continue
			else:
				
				tags_checker["examples1"] = True
				reading_positives= False	
				reading_negatives=True

		else:
			#Log.close()
			#raise Exception("Unexpected tag found [%s] on line %d"%(tmp,line))
			pass

	elif reading_hypothesis:
		hypothesis_reader+=tmp.replace("\n","")
		if "." in hypothesis_reader :
			reading_positives= True
			reading_hypothesis=False
			

			head = hypothesis_reader.split(":-")[0].strip(" ")
			tail = hypothesis_reader.split(":-")[1].strip(" ")
			tail = create_list_predicates(tail.replace(" ","").strip(" ").strip("\n"))
			

			new_rule["head"] = head
			new_rule["tail"] = tail
	

	elif reading_positives:
		if prediction_target in tmp:
			positive = {'name': "", 'content':[]}
			
			positive_string = tmp.strip("\n").strip(" ")
			name = positive_string.split("(")[0]
			#print(positive_string.split("(")[1])
			content = positive_string.split("(")[1]
			content = content.split(")")[0].split(",")

			#print(content)
		
			positive["name"] = name
			positive["content"] = content
			#print("positive: %s"%positive)
			new_rule["positives"].append(positive)
			#print("HERE")
			#print(l)

	elif reading_negatives:
		if prediction_target in tmp:
			negative = {'name': "", 'content':[]}
			negative_string = tmp.strip("\n").strip(" ")
			name = negative_string.split("(")[0]
			content = negative_string.split("(")[1]
			content = content.split(")")[0].split(",")
			
			negative["name"] = name
			negative["content"] = content

			#print("negative: %s"%negative)
			new_rule["negatives"].append(negative)
			#print("HERE")
			#print(l)

		
		

Log.close()

#Maybe introduce a dicionary during preprocess?



rule_list.append(new_rule)

#print(rule_list[0])
checker_validate(tags_checker)
#print(json.dumps(rule_list,indent=4))





from rulestatistics import Rule_Statistics
from literals import Literal
from scores import Score_1,Score_2,Precision,Recall,F1,Positivec,Negativec
from logger import Logger




print("Pos: "+ str(len(positives)))


##START

statistic_tool = Rule_Statistics(rule_list,facts,positives,negatives,lifted_rw)


if not os.path.exists("uniq_rules.pickle"):
	count,uniq_rules  = statistic_tool.equivalent_rules(Logger("Equivant#"),equalities)
	with open("data/uniq_rules.pickle", "wb") as f:
		pickle.dump(uniq_rules, f)

else: 
	with open("data/uniq_rules.pickle", 'rb') as file:
		uniq_rules = pickle.load(file)


'''
step =math.ceil(len(uniq_rules)/96)

result =0
while result < len(uniq_rules):
	if result+step > len(uniq_rules):
		print([result,len(uniq_rules)])
	else:
		print([result,result+step])
	result+=step
'''

limits = [int(sys.argv[1]),int(sys.argv[2])]
file_name = "Correlations"+sys.argv[1]+sys.argv[2]


print("Rules length: %d\n"%len(uniq_rules))
if limits[1]> len(uniq_rules):
	limits[1] = len(uniq_rules)

statistic_tool.calculate_correlations_all_rules(uniq_rules,Logger(file_name),limits)




quit()
##END OF THE CODE
