import subprocess
import validate
import matplotlib.pyplot as plt
import os
import json
import math

def create_list_predicates(string):
	#print(string)
	p_list =[]
	tmp_str=""
	is_inside = False
	for c in string:
		#print(c) 
		#print(is_inside)
		#print(tmp_str)
		if c=="(":
			tmp_str+=c
			is_inside = True
		elif c==")":
			tmp_str+=c
			is_inside = False
		elif c == "," and not is_inside:
			#print("HERE")
			p_list.append(tmp_str)
			tmp_str=""
		else:
			tmp_str+=c

	if tmp_str!= "" and "!" not in tmp_str:
		p_list.append(tmp_str)


	return p_list

def process_equalities(path):
	f = open(path,"r")
	equalities = {}
	for line in f:
		print(line)
		slitted_line = line.split("=")
		arg1 =  slitted_line[0].strip()
		arg2 =  slitted_line[1].strip()
		equalities[arg1] = arg2
		equalities[arg2] = arg1
		

	f.close()
	return equalities



print("Loading facts...\n")
facts =validate.process_literals("data/facts.txt")

print("Loading negatives...\n")
negatives = validate.process_literals("data/neg.txt")

print("Loading positives...\n")
positives = validate.process_literals("data/pos.txt")


print("Loading lifted random walks...\n")
lifted_rw = validate.process_lifted("data/lifted.tree")

equalities = process_equalities("data/equalities.txt")




#data consistence checker
num_lines = sum(1 for _ in open("data/facts.txt"))
is_facts_consistent = len(facts) == num_lines

num_lines = sum(1 for _ in open("data/neg.txt"))
is_negatives_consistent = len(negatives)==num_lines

num_lines = sum(1 for _ in open("data/pos.txt"))
is_positives_consistent = len(positives)==num_lines

num_lines = sum(1 for _ in open("data/lifted.tree"))
is_lifts_consistent = len(lifted_rw)==num_lines




#consistence with number of lines check
if not is_facts_consistent:
	raise Exception("Number of lines inconsistent with the number of facts")
if not is_negatives_consistent:
	raise Exception("Number of lines inconsistent with the number of negatives")
if not is_positives_consistent:
	raise Exception("Number of lines inconsistent with the number of positives")
if not is_lifts_consistent:
	raise Exception("Number of lines inconsistent with the number of lifts")



#take the name of the first positive predicate to take the target name
prediction_target = positives[0]["name"]

#Check existence of the file where the data generated by aleph would be
if not os.path.exists("Logs/LiftFINALLOG.txt"):
	raise Exception("Logs/LiftFINALLOG.txt missing")


log_file = "Logs/LiftFINALLOG.txt"
Log = open(log_file,"r")

####################################################
#
# READING ALEPH data
#
####################################################

log_file = "Logs/LiftFINALLOG.txt"
Log = open(log_file,"r")


#line counter debug effects
line =0

rule_list= []





#VARIABLES TO RESET
new_rule = {"head":"","tail":[],"positives":[],"negatives":[]}
tags_checker = {
	"consulting pos examples":False,
	"consulting neg examples":False,
	"hypothesis":False,
	"examples1":False,
	"examples2":False,	
}
hypothesis_reader =""
reading_hypothesis=False
reading_positives = False
reading_negatives = False
def checker_validate(checker):
	#print(checker)
	for key in checker.keys():
		if not checker[key]:
			raise Exception("[%s] tag not found on format file on line %d"%(key,line))

		


for l in Log:
	tmp = l.strip()
	line+=1
	#start to read a new rule
	
	#print("reading_positives: %d reading_negatives: %d reading_hypothesis: %d"%(reading_positives,reading_negatives,reading_hypothesis))
	
	if "A L E P H" in tmp:
		if new_rule["head"]!= "":
			checker_validate(tags_checker)

			rule_list.append(new_rule)
			#print(new_rule)
			


		#reset dictionaries
		new_rule = {"head":"","tail":[],"positives":[],"negatives":[]}
		tags_checker = {"consulting pos examples":False,"consulting neg examples":False,"hypothesis":False,"examples1":False,"examples2":False,	}
		reading_hypothesis=False
		reading_positives = False
		reading_negatives = False
		hypothesis_reader=""

	#Reat ALL TAGS
	elif len(tmp) > 0 and tmp[0] == "[":
		tmp = tmp.split("]")[0].replace("[","").strip()
		#print(tmp)

		if tmp == "hypothesis":
			tags_checker[tmp] =True
			reading_hypothesis= True

		elif tmp == "consulting pos examples":
			tags_checker[tmp] =True
		elif tmp == "consulting neg examples":
			tags_checker[tmp] =True

		elif tmp == "examples covered":
			reading_negatives=False
			
			if tags_checker["examples1"]:
				if tags_checker["examples2"]:
					Log.close()
					raise Exception("Unexpected tag found [%s]"%tmp)
				
				tags_checker["examples2"] = True
				
				continue
			else:
				
				tags_checker["examples1"] = True
				reading_positives= False	
				reading_negatives=True

		else:
			#Log.close()
			#raise Exception("Unexpected tag found [%s] on line %d"%(tmp,line))
			pass

	elif reading_hypothesis:
		hypothesis_reader+=tmp.replace("\n","")
		if "." in hypothesis_reader :
			reading_positives= True
			reading_hypothesis=False
			

			head = hypothesis_reader.split(":-")[0].strip(" ")
			tail = hypothesis_reader.split(":-")[1].strip(" ")
			tail = create_list_predicates(tail.replace(" ","").strip(" ").strip("\n"))
			

			new_rule["head"] = head
			new_rule["tail"] = tail
	

	elif reading_positives:
		if prediction_target in tmp:
			positive = {'name': "", 'content':[]}
			
			positive_string = tmp.strip("\n").strip(" ")
			name = positive_string.split("(")[0]
			#print(positive_string.split("(")[1])
			content = positive_string.split("(")[1]
			content = content.split(")")[0].split(",")

			#print(content)
		
			positive["name"] = name
			positive["content"] = content
			#print("positive: %s"%positive)
			new_rule["positives"].append(positive)
			#print("HERE")
			#print(l)

	elif reading_negatives:
		if prediction_target in tmp:
			negative = {'name': "", 'content':[]}
			negative_string = tmp.strip("\n").strip(" ")
			name = negative_string.split("(")[0]
			content = negative_string.split("(")[1]
			content = content.split(")")[0].split(",")
			
			negative["name"] = name
			negative["content"] = content

			#print("negative: %s"%negative)
			new_rule["negatives"].append(negative)
			#print("HERE")
			#print(l)

		
		

Log.close()

#Maybe introduce a dicionary during preprocess?



rule_list.append(new_rule)

#print(rule_list[0])
checker_validate(tags_checker)
#print(json.dumps(rule_list,indent=4))





from rulestatistics import Rule_Statistics
from literals import Literal
from scores import Score_1,Score_2,Precision,Recall,F1,Positivec,Negativec
from logger import Logger




print("Pos: "+ str(len(positives)))


##START

statistic_tool = Rule_Statistics(rule_list,facts,positives,negatives,lifted_rw)





scores = {
	"positive":Positivec(),
	"negative":Negativec(),
	"score1":Score_1(),
	"score2":Score_2(),
	"precision":Precision(),
	"recall":Recall(),
	"f1":F1()
}


statistic_tool.get_rule_info(Logger("rule_info.txt"))
statistic_tool.show_rule_coverage(Logger("coverage.txt"))
statistic_tool.show_weak_rules(Logger("weak_rules.txt"))
statistic_tool.show_uncoveraded_examples(Logger("uncovered.txt"))
statistic_tool.show_number_of_rules_covering_examples(Logger("rules_per_example.txt"))

statistic_tool.Rank_Rules_by_score(scores["score1"],Logger("Score1_ranking.txt"))
statistic_tool.Rank_Rules_by_score(scores["score2"],Logger("Score2_ranking.txt"))
statistic_tool.Rank_Rules_by_score(scores["precision"],Logger("Precision_ranking.txt"))
statistic_tool.Rank_Rules_by_score(scores["recall"],Logger("Recall_ranking.txt"))
statistic_tool.Rank_Rules_by_score(scores["f1"],Logger("F1_ranking.txt"))
statistic_tool.number_of_rules_of_each_size(Logger("Number_of_rules_by_size.txt"))

scores_list = [scores["precision"],scores["recall"],scores["f1"]]
statistic_tool.plot_score(scores_list)

scores_list = [scores["positive"],scores["negative"]]
statistic_tool.plot_score(scores_list)


all_rules = {
	2:statistic_tool.slice_rules_by_size(2),
	3:statistic_tool.slice_rules_by_size(3),
	4:statistic_tool.slice_rules_by_size(4),
	5:statistic_tool.slice_rules_by_size(5),
	6:statistic_tool.slice_rules_by_size(6)
}



scores_list = [scores["recall"],scores["precision"],scores["f1"]]
statistic_tool.plot_scores_for_all_sizes(scores_list)

#FIND OUT HOW TO PUT TOTALS ON THE PLOT
scores_list = [scores["positive"],scores["negative"]]
statistic_tool.plot_scores_for_all_sizes(scores_list)




statistic_tool.calculate_all_sizes_average_degree()

statistic_tool.calculate_improvements_for_all_sizes(scores["f1"])

statistic_tool.get_outliers(scores["precision"],Logger("outliers.txt"))


statistic_tool.get_origins(Logger("origin_rules.txt"))



#outliers = statistic_tool.get_outliers(scores["positive"],Logger(),rules = all_rules[5])

#print("-"*20)
#print("OUT")
#print(outliers)
#print("-"*20)
#rules2= statistic_tool.slice_rules_by_size(2)



#statistic_tool.Rank_Rules_by_score(scores["recall"],Logger(),rules=rules2)

#statistic_tool.Rank_Rules_by_score(scores["positive"],Logger(),rules=rules2)
#statistic_tool.Rank_Rules_by_score(scores["negative"],Logger(),rules=rules2)
#statistic_tool.calculate_correlations_all_rules()


import time


start = time.time()
count,uniq_rules  = statistic_tool.equivalent_rules(Logger("Equivant#"),equalities)
end = time.time()
print(f"Total runtime of the program is {end - start} seconds")

print("Total rules without equivalents: %d"%(len(uniq_rules)))
#statistic_tool.rules = uniq_rules
quit()

statistic_tool.Rank_Rules_by_score(scores["score1"],Logger("UNIQ_Score1_ranking.txt"),uniq_rules)
statistic_tool.Rank_Rules_by_score(scores["score2"],Logger("UNIQ_Score2_ranking.txt"),uniq_rules)
statistic_tool.Rank_Rules_by_score(scores["precision"],Logger("UNIQ_Precision_ranking.txt"),uniq_rules)
statistic_tool.Rank_Rules_by_score(scores["recall"],Logger("UNIQ_Recall_ranking.txt"),uniq_rules)
statistic_tool.Rank_Rules_by_score(scores["f1"],Logger("UNIQ_F1_ranking.txt"),uniq_rules)
statistic_tool.number_of_rules_of_each_size(Logger("UNIQ_Number_of_rules_by_size.txt"),uniq_rules)
#statistic_tool.plot_scores_for_all_sizes(scores_list,uniq_rules,)

scores_list = [scores["precision"],scores["recall"],scores["f1"]]
statistic_tool.plot_score(scores_list,prefix="UNIQ",rules = uniq_rules)

scores_list = [scores["positive"],scores["negative"]]
statistic_tool.plot_score(scores_list,prefix="UNIQ",rules = uniq_rules)

scores_list = [scores["recall"],scores["precision"],scores["f1"]]
statistic_tool.plot_scores_for_all_sizes(scores_list,prefix="UNIQ_",rules = uniq_rules)

#FIND OUT HOW TO PUT TOTALS ON THE PLOT
scores_list = [scores["positive"],scores["negative"]]
statistic_tool.plot_scores_for_all_sizes(scores_list,prefix="UNIQ",rules = uniq_rules)

statistic_tool.calculate_correlations_all_rules(uniq_rules,Logger("Correlations.txt"))

statistic_tool.dfs("stat_logs/Correlations.txt",Logger("clusters.txt"))


quit()
##END OF THE CODE



print(len(lifted_rw))
print(len(rule_list))


zero_negatives =0
zero_positives =0
for r in range(len(rule_list)):
	coverage =0
	for p in positives:
		for p2 in rule_list[r]["positives"]:
			#print("positive in rule_list %s " %p2["content"])
			#print("positive in positives %s "%p["content"])
			
			if p["content"]== p2["content"]:
				#print("MATCH FOUND")
				
				
				coverage +=1
				break
	print("rule#: " + str(r+1)+" " + str(rule_list[r]["head"]) +" :- " +str(rule_list[r]["tail"]) + " covered %d of %d positives"%(coverage,len(positives)) ) 
	rule_list[r]["positive_c"] = coverage
	if coverage==0:
		zero_positives+=1

print("------------------------------------------")
for r in range(len(rule_list)):

	coverage=0
	for p in negatives:
		for p2 in rule_list[r]["negatives"]:
			#if p["content"]== p2["content"]:

			if p["content"]== p2["content"]:
				coverage +=1
				
				break
	print("rule#: " + str(r+1)+" " + str(rule_list[r]["head"]) +" :- " +str(rule_list[r]["tail"]) + " covered %d of %d negatives" %(coverage,len(negatives)) )
	
	#print(len(rule_list[r]["negatives"]))
	#print("%s :- %s " % (rule_list[r]["head"],rule_list[r]["tail"]))
	rule_list[r]["negative_c"] = coverage
	if coverage==0:
		zero_negatives+=1 

both_zero =0
for r in range(len(rule_list)):
	if rule_list[r]["negative_c"] == 0 and  rule_list[r]["positive_c"] ==0:
		both_zero+=1 




print("\n\n\n")

number_of_positives_uncovered =0
number_of_negatives_uncovered =0
positive =1
for p in positives:
	covered = False
	rules_covering_count =0
	for r in rule_list:
		for p2 in r["positives"]:
			if p["content"]== p2["content"]:
				rules_covering_count +=1
				covered = True
				break
	if covered:
		number_of_positives_uncovered+=1
	print("#%d %s%s was covered by %d #rules " % (positive,p["name"],str(p["content"]),rules_covering_count))
	positive+=1

print("------------------------------------------")
negative=1
for p in negatives:
	covered = False
	rules_covering_count =0
	for r in rule_list:
		for p2 in r["negatives"]:
			if p["content"]== p2["content"]:
				rules_covering_count +=1
				covered = True
				break
	if covered:
		number_of_negatives_uncovered+=1
	print("#%d %s%s was covered by %d #rules " % (negative,p["name"],str(p["content"]),rules_covering_count))
	negative+=1


for r in range(len(rule_list)):
	
	rule_list[r]["FP"] = len(negatives)- rule_list[r]["negative_c"]
	rule_list[r]["FN"] = len(positives)-rule_list[r]["positive_c"] 

	rule_list[r]["AFP"] = rule_list[r]["FN"] 
	rule_list[r]["AFN"] = rule_list[r]["FP"]




print("\nSUMMARY:")
print("%d rules processed" % (len(rule_list)))
print("%d out of %d positives where covered corresponding to a coverage of %f " % (number_of_positives_uncovered,len(positives), number_of_positives_uncovered/len(positives) ))
print("%d out of %d negatives where covered corresponding to a coverage of %f " % (number_of_negatives_uncovered,len(negatives),number_of_negatives_uncovered/len(negatives)))
print("%d out of %d rules are useless for positives " %( zero_positives,len(rule_list)))
print("%d out of %d rules are useless for negatives " %( zero_negatives,len(rule_list)))
print("%d out of %d rules are useless for negatives and positives " %( both_zero,len(rule_list)))
#print(positives)





def score(rule):
	return rule["positive_c"]-rule["negative_c"]

def score2(rule):
	return rule["negative_c"]-rule["positive_c"]


def presision(rule):
	tp = rule["positive_c"]
	if tp + rule["FP"]==0:
		return 0
	return tp/(tp + rule["FP"])


def recall(rule):
	tp = rule["positive_c"]
	if tp + rule["FN"] ==0:
		return 0
	return tp/(tp + rule["FN"])

def f1(rule):
	recall_score = recall(rule)
	presision_score = presision(rule)
	if presision_score+recall_score ==0:
		return 0
	score = 2* recall_score*presision_score/(presision_score+recall_score)
	return score


def antipresision(rule):
	tp = rule["negative_c"]
	if tp+ rule["AFP"] ==0:
		return 0
	return tp/(tp+ rule["AFP"])


def antirecall(rule):
	tp = rule["negative_c"]
	if tp + rule["AFN"]:
		return 0
	return tp/(tp + rule["AFN"])


def antif1(rule):
	recall_score = antirecall(rule)
	presision_score = antipresision(rule)
	if presision_score+recall_score ==0:
		return 0
	score = 2 *recall_score*presision_score/(presision_score+recall_score)
	return score


print(len(rule_list))
print("\n\nRANKING RULES POSITIVE:")


rule_list.sort(key=score )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),score(r)))


print("\n\nRANKING RULES NEGATIVE:")


rule_list.sort(key=score2 )

for r in rule_list:
	print(" %s :- %s with the score of %f"%(str(r["head"]),str(r["tail"]),score2(r)))



print("\n\nRANKING RULES PRECISION:")


rule_list.sort(key=presision )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),presision(r)))


print("\n\nRANKING RULES RECALL:")


rule_list.sort(key=recall )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),recall(r)))

print("\n\nRANKING RULES F1")
rule_list.sort(key=f1 )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),f1(r)))

print("\n\nRANKING RULES ANTIRECALL")
rule_list.sort(key=antirecall )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),antirecall(r)))


print("\n\nRANKING RULES ANTIPRECISION")
rule_list.sort(key=antipresision )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),antipresision(r)))


print("\n\nRANKING RULES ANTIF1")
rule_list.sort(key=antif1 )

for r in rule_list:
	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),antif1(r)))




pos_coverages = []
neg_coverages = []
pos_coverages2 = []
neg_coverages2 = []
scores1 = []
scores2 = []
recalls = []
presisions =[]
f1s = []
antirecalls = []
antipresisions =[]
antif1s = []

for r in rule_list:
	scores1.append(score(r))
	scores2.append(score2(r))
	recalls.append(recall(r))
	presisions.append(presision(r))
	f1s.append(f1(r))
	antirecalls.append(antirecall(r))
	antipresisions.append(antipresision(r))
	antif1s.append(antif1(r))
	pos_coverages.append(r["positive_c"]/len(positives))
	neg_coverages.append(r["negative_c"]/len(negatives))
	pos_coverages2.append(r["positive_c"])
	neg_coverages2.append(r["negative_c"])



absolute_coverage = {
	"positive coverage":pos_coverages2,
	"negative coverage":neg_coverages2
}

coverage = {
	"positive coverage":pos_coverages,
	"negative coverage":neg_coverages,
}


fig, ax = plt.subplots()
ax.boxplot(absolute_coverage.values(),showmeans=True)
ax.set_xticklabels(absolute_coverage.keys())


plt.savefig("absolute_coverage.jpg")
plt.close()


fig, ax = plt.subplots()
ax.boxplot(coverage.values(),showmeans=True)
ax.set_xticklabels(coverage.keys())
ax.set_ylim([0, 1])
plt.savefig("coverage.jpg")
plt.close()	
	
scores12 = {
	"score":scores1,
	"score2":scores2,
}

fig, ax = plt.subplots()
ax.boxplot(scores12.values(),showmeans=True)
ax.set_xticklabels(scores12.keys())
ax.set_ylim([0, 1])
plt.savefig("scores12.jpg")
plt.close()

catalogation ={


"recall":recalls,
"precision":presisions,
"f1":f1s,
"antirecall":antirecalls,
"antiprecision":antipresisions,
"antif1":antif1s
}

fig, ax = plt.subplots()
ax.boxplot(catalogation.values(),showmeans=True)
ax.set_xticklabels(catalogation.keys())
ax.set_ylim([0, 1])
plt.savefig("other scores.jpg")









sizes = [2,3,4,5,6]
quantity = [[],[],[],[],[]]
pos_coverage = [[],[],[],[],[]]
neg_coverage = [[],[],[],[],[]]
pos_coverage2 = [[],[],[],[],[]]
neg_coverage2 = [[],[],[],[],[]]
score_mean = [[],[],[],[],[]]
score2_mean = [[],[],[],[],[]]
presision_mean = [[],[],[],[],[]]
recall_mean = [[],[],[],[],[]]
f1_mean = [[],[],[],[],[]]
antirecall_mean = [[],[],[],[],[]]
antiprecision_mean = [[],[],[],[],[]]
antif1_mean = [[],[],[],[],[]]


for r in rule_list:
	pos_coverage[len(r["tail"])-2].append(r["positive_c"]/len(positives))
	neg_coverage[len(r["tail"])-2].append(r["negative_c"]/len(negatives))
	pos_coverage2[len(r["tail"])-2].append(r["positive_c"])
	neg_coverage2[len(r["tail"])-2].append(r["negative_c"])
	score_mean[len(r["tail"])-2].append(score(r))
	score2_mean[len(r["tail"])-2].append(score2(r))
	presision_mean[len(r["tail"])-2].append(presision(r))
	recall_mean[len(r["tail"])-2].append(recall(r))
	f1_mean[len(r["tail"])-2].append(f1(r))
	antirecall_mean[len(r["tail"])-2].append(antirecall(r))
	antiprecision_mean[len(r["tail"])-2].append(antipresision(r))
	antif1_mean[len(r["tail"])-2].append(antif1(r))

	if len(r["tail"]) ==2:
		print()
		print(r["tail"])
		print("recall: %f"% recall(r) )
		print("precision: %f"% presision(r) )
		print("F1: %f"%f1(r))
		print("Positive coverage: %f"% (r["positive_c"]/len(positives) ))
		print("Negative coverage: %f"% (r["negative_c"]/len(negatives)))
		print("FN: %f"%(r["FN"] ))
		print("FP: %f"%(r["FP"] ))


	

	
def mean_it(l):
	if len(l)==0:
		return 0
	return sum(l)/len(l)


for r in range(len(sizes)):
	print("%d rules of size %d" %(len(pos_coverage[r]),sizes[r]))
	print("average positive coverage of %f" %(mean_it(pos_coverage2[r])))
	print("average negative coverage of %f" %(mean_it(neg_coverage2[r])))
	print("average score of %f" %(mean_it(score_mean[r])))
	print("average score2 of %f" %(mean_it(score2_mean[r])))
	print("average precision of %f" %(mean_it(presision_mean[r])))
	print("average recall of %f" %( mean_it(recall_mean[r]) ))
	print("average f1 of %f" %( mean_it(f1_mean[r]) ))
	print("average antirecall of %f" %( mean_it(antirecall_mean[r]) ))
	print("average antiprecision of %f" %( mean_it(antiprecision_mean[r]) ))
	print("average antif1 of %f" %( mean_it(antif1_mean[r]) ))
	print("\n")


	coverage = {
	"positive coverage":pos_coverage[r],
	"negative coverage":neg_coverage[r]
	}

	absolute_coverage = {
	"positive coverage":pos_coverages2,
	"negative coverage":neg_coverages2
	}

	fig, ax = plt.subplots()
	ax.boxplot(absolute_coverage.values(),showmeans=True)
	ax.set_xticklabels(absolute_coverage.keys())
	ax.set_ylim([0, 1])
	plt.savefig("absolute coverage by rule size %d.jpg" % (sizes[r]))

	plt.close()

	fig, ax = plt.subplots()
	ax.boxplot(coverage.values(),showmeans=True)
	ax.set_xticklabels(coverage.keys())
	ax.set_ylim([0, 1])
	plt.savefig("coverage by rule size %d.jpg" % (sizes[r]))
	plt.close()

	
	scores12 = {
	"score":score_mean[r],
	"score2":score2_mean[r]
	}

	fig, ax = plt.subplots()
	ax.boxplot(scores12.values(),showmeans=True)
	ax.set_xticklabels(scores12.keys())
	ax.set_ylim([0, 1])
	plt.savefig("scores12 by rule size %d.jpg" % (sizes[r]))
	plt.close()


	catalogation ={
	
	
	"recall":recall_mean[r],
	"precision":presision_mean[r],
	"f1":f1_mean[r],
	"antirecall":antirecall_mean[r],
	"antiprecision":antiprecision_mean[r],
	"antif1":antif1_mean[r]
	}

	fig, ax = plt.subplots()
	ax.boxplot(catalogation.values(),showmeans=True)
	ax.set_xticklabels(catalogation.keys())
	ax.set_ylim([0, 1])
	plt.savefig("other scores by rule size %d.jpg" % (sizes[r]))
	plt.close()



quit()
rule_list.sort(key=f1 )

print(len(rule_list))
k= 5
print(len(rule_list)/k)

step = math.floor(len(rule_list)/k)
elements_for_k = [step*(i+1) +1 for i in range(k)]

print("Elements: %s" % str(elements_for_k))
fold = 0
f_measures = [0,0]
for i in range(len(rule_list)):
	rule = "(%s :-  "%rule_list[i]["head"] #_venue(A,C), author(C,D), haswordauthor(D,H), _haswordvenue(H,B), !).
	rule=rule.replace("B)","B,0)")

	
	for predicate in rule_list[i]["tail"]:
		rule+=predicate.replace(",",", ")+", "
	rule+="!)."
	rule = rule.replace(", !"," , !").replace("twin","_")
	print(rule)
	
	if i==0 or i==elements_for_k[fold-1]:
		print("fold: %d "%(fold)  + str(f_measures))
		fold +=1
		if i!=0:
			f.close()
		f = open("folder_k%d"%fold,"w")

		f_measures = [0,0]
	f.write(rule+"\n")
	#print("fold: %d \n f1: %f\ncover: %d %d \n\n"%(fold,f1(rule_list[i]),rule_list[i]["positive_c"],rule_list[i]["negative_c"]) )
	f_measures[0] +=f1(rule_list[i])
	f_measures[1] +=1

	

f.close()

#for r in rule_list:
#	print(" %s :- %s with the score of %f" %(str(r["head"]),str(r["tail"]),f1(r)))